# Generated by Django 6.0.6 on 2026-06-27 16:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('SIGN', 'Signature'), ('VERIFY', 'Verification')], max_length=10)),
                ('document_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(blank=True, max_length=50, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('details', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='SigningKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('public_key', models.TextField()),
                ('private_key', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('filename', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('file_hash', models.CharField(max_length=64)),
                ('signature', models.TextField()),
                ('signer_name', models.CharField(max_length=255)),
                ('public_key', models.TextField()),
                ('pdf_file', models.FileField(upload_to='signed_pdfs/')),
                ('qr_code_file', models.ImageField(upload_to='qrs/')),
                ('is_latest', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('document_id', 'version')},
            },
        ),
    ]
